### ISSUE TITLE
Error in getblocking object.

### ISSUE THREAD

**Issue by VIkash2601** [agnosticdev/Blog-Examples#1]
Traceback (most recent call last):
  File "client_socket.py", line 18, in <module>
    if s.getblocking():
AttributeError: 'socket' object has no attribute 'getblocking'

**in both client_socket and server_socket files**

**Comment by agnosticdev** [comment]
@VIkash2601 my apologies on getting back to you so late.  Are you still having this issue?

**Comment by agnosticdev** [comment]
Please re-open if this issue is still happening.
